# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Geek Wing
email: puahhuiying@gmail.com
description: The geeky adventures of Wing. Technology, kids development and fitness.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thegeekwing.com" # the base hostname & protocol for your site, e.g. http://example.com
imgurl: "https://res.cloudinary.com/thegeekwing/image/upload"
facebook_app_id: 1452029651542835

# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed

include: ["_pages"]
permalink: pretty

collections:
  category:
    output: true

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: "post"
    is_post: true
- scope:
    path: ""
    type: category
  values:
    layout: "category"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
